version: '3.1'

services:
  urlshortener:
    build: .    
    restart: always
    container_name: urlshortener
    ports:
      - 8182:8080
    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: mongod
    ports:  
     - 27017:27017
    restart: always